### ISSUE TITLE
genome.fa command not found

### ISSUE THREAD

**Issue by arodel21** [guertinlab/Tn5bias#2]
Hello!

First of all, thank you for your great work!

I was wondering if you could help me with the following error 

`/usr/bin/bash: line 1: GRCz11.fa: command not found`

I am getting it when running the command

`seqOutATACBias masks -i=$BAM -g=GRCz11.fa -p=1 -r=50 -c=NO`

Is this a bug? How could I solve it?

Thanks in advance.

**Comment by JWolpe** [comment]
Hi @arodel21, thank you for using our software!
    
This is not the expected function. To help troubleshoot, could you please try entering `seqOutATACBias`?
    
If the output from that command isn't `command not found` , next enter:
`export DEVMODE="true"`
`seqOutATACBias depend`
If you get something like:
```
Cleanup (-c or --cleanup)= TRUE
Read Length (-r or --readlength)= 60
Input (-i or --input)=
Genome (-g or --genome)=
Processors (-p or --processors)=
Command = depend
Outfile =
Checked dependencies installed
```
    
Then please try entering:
`seqOutATACBias masks --input=${BAM} --genome=GRCz11.fa --processors=1 --readlength=50 --cleanup=NO`

Please let me know if this helps, or if you get any new error messages. Addtionally, could you try entering the BAM file name manually instead of using a variable?

**Comment by arodel21** [comment]
Hi @JWolpe! Thank you so much for your reply.

When doing
```
export DEVMODE="true"
seqOutATACBias depend
```
It installed a few dependencies missing and finished succesfully.

But when I run 
`seqOutATACBias masks --input=${BAM} --genome=GRCz11.fa --processors=1 --readlength=50 --cleanup=NO`
I keep on getting the same errors

I have attached the log files here
[866851_bias_mask_out.txt](https://github.com/guertinlab/Tn5bias/files/14270166/866851_bias_mask_out.txt)
[866851_bias_mask_err.txt](https://github.com/guertinlab/Tn5bias/files/14270169/866851_bias_mask_err.txt)

**Comment by JWolpe** [comment]
Hi @arodel21, thank you for trying to troubleshoot this with me and for supplying logs!

After some more analysis, it seems the error does not directly relate to the script content itself but rather how the script or one of its commands is executed.

We can try a couple of different things to correct this:
First, please simply enter:
`seqOutATACBias`
And let me know the output response

Next, please reenter:
```
export DEVMODE="true"
seqOutATACBias depend
```
If the output from this does not look like:
```
Cleanup (-c or --cleanup)= TRUE
Read Length (-r or --readlength)= 60
Input (-i or --input)=
Genome (-g or --genome)=
Processors (-p or --processors)=
Command = depend
Outfile =
Checked dependencies installed
```
There is something preventing the dependencies from being installed.

Then, please try entering the BAM file name manually instead of using a variable, like this:
`seqOutATACBias masks --input=FILENAME.bam --genome=GRCz11.fa --processors=1 --readlength=50 --cleanup=NO`

After this, please put the input and genome fields in quotation marks, like so:
`seqOutATACBias masks --input="FILENAME.bam" --genome="GRCz11.fa" --processors=1 --readlength=50 --cleanup=NO`

Next please make sure that the directory in which you are executing this in is empty, aside for the input files. From the log entry:
`Error: output BED file clean_merged_Citrine_ATAC_Jul2015_zv10_not_scaled.bed already exists!`
It appears that some of the files which you are attempting to create are already in the folder.


Finally, please also attempt to run this locally while troubleshooting, instead of on an HPC using SLURM. I was able to successfully install and run this software on a linux and windows machine locally since your ticket. This may be an issue with the setup of your HPC environment which could be solved if you try to run the software locally. If you'd like to download a small test data set that is more manageable for a laptop or desktop, you can find the test data set I used in section 3.1 of the seqOutATACBias_workflow_Vignette in this repo. It should process in less than 15 minutes and take up less then 1Gb of storage space.

Hopefully this helps!

**Comment by arodel21** [comment]
Hi @JWolpe 

I tried with all the instructions and it keeps on failing.

This is the command that I ran

`seqOutATACBias masks --input="subsample_sort.bam" --genome="GRCz11.fa" --processors=1 --readlength=50 --cleanup=NO`

I attached both the out and the errors log files. Also I prepared a small subsample of my dataset in case you would help me figure out what's wrong. I am getting the same errors with this file.

[866851_bias_mask_out.txt](https://github.com/guertinlab/Tn5bias/files/14375529/866851_bias_mask_out.txt)
[866851_bias_mask_err.txt](https://github.com/guertinlab/Tn5bias/files/14375531/866851_bias_mask_err.txt)
[subsample_sort.bam.gz](https://github.com/guertinlab/Tn5bias/files/14375532/subsample_sort.bam.gz)

**Comment by guertinlab** [comment]
when you provide the command to the Terminal/command line:
`which bash`, what is the output? 

I also see the error: `Error: output BED file clean_merged_Citrine_ATAC_Jul2015_zv10_not_scaled.bed already exists!
`, so you should delete this file before running seqOutBias. 

I am not an expert on seqOutATACBias, but have you successfully implemented seqOutBias? the error seems to be that you are at some point calling `GRCz11.fa` as a function.

-Mike

**Comment by arodel21** [comment]
Hello again @guertinlab @JWolpe 

when I do `which bash` I get `/usr/bin/bash`.

The error `Error: output BED file clean_merged_Citrine_ATAC_Jul2015_zv10_not_scaled.bed already exists!` is fixed if I delete the temporary files.

I am not calling GRCz11.fa at any point. It seems like GRCz11.fa **is being called as a script or function by seqOutATACBias**, because my script only contains `seqOutATACBias masks --input="subsample_sort.bam" --genome="GRCz11.fa" --processors=1 --readlength=50 --cleanup=NO` and the error keeps on happening if I run the command directly on the terminal.

Would it be possible for you to replicate the execution youself with the GRCz11.fa, which you can find in NCBI ([link](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000002035.6/))?

Thanks again.
Best wishes.

**Comment by JWolpe** [comment]
Hi @arodel21,

Please let me know the output of:
`which seqOutATACBias`
`which seqOutBias`

I am glad we were able to fix the bed file already exists error.

I understand that you are not calling GRCz11.fa at any point. These errors often happen when an environment is misconfigured. This is why I ask that you conduct these tests on a local machine, and not in an HPC environment using a SLURM job manager. Your error logs indicate that you are attempting to run seqOutATACBias in an HPC environment using a SLURM job manager. I was able to install and run seqOutATACBias using the above command with your provided bam file. The attached output bigWig file is
from this run, and you can see a genome view of some of the scaled reads below. I was unable to reproduce these errors on a Windows machine from a fresh install. Please let me know if you find a way that I can further investigate this issue.
 
![RE_scaled_IGV](https://github.com/guertinlab/Tn5bias/assets/66966976/76e087e4-c600-43e2-90f8-952e91028395)
[subsample_sort_RE_scaled.bigWig.gz](https://github.com/guertinlab/Tn5bias/files/14487833/subsample_sort_RE_scaled.bigWig.gz)

Best regards

**Comment by arodel21** [comment]
Hi @JWolpe! Thanks for your reply.

Indeed there is an issue during the installation of seqOutBias. I have submitted an issue on their github repository.

Will keep you posted.

**Comment by arodel21** [comment]
Hi again @JWolpe!

I got seqOutBias working now! So I ran the program again in a local machine from the cluster that I am working on. I am still getting the same errors though:

```
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
/usr/bin/bash: line 1: GRCz11.fa: command not found
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXNNNNNNCNXXXXXXXXXXXXXXXXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXNNNNNCNNXXXXXXXXXXXXXXXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXNNNNCNNNXXXXXXXXXXXXXXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXNNNCNNNNXXXXXXXXXXXXXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXNNCNNNNNXXXXXXXXXXXXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCNNNNNNNXXXXXXXXXXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXNNNNNNNXXXXXXXXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXNNNNNNNXXXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXXNNNNNNNXXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXXXNNNNNNNXXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXXXXNNNNNNNXXXXXX.bigWig
Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXXXXXXNNNNNNNXXXX.bigWig
Error: The requested file (clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXNNNNNNCNXXXXXXXXXXXXXXXXXXXXXX.bedGraph) could not be opened. Error message: (No such file or directory). Exiting!
```
I have attached the log here
[seqout_log.txt](https://github.com/guertinlab/Tn5bias/files/14523571/seqout_log.txt)

I really don't know how to proceed... Any advice would be welcomed

**Comment by JWolpe** [comment]
Hi @arodel21,

Great to hear that you got the dependencies working!

I think you may have misunderstood me when I said "local machine". I meant a local computer not connected to your HPC environment/cluster, such as a desktop computer. You would then not SSH or otherwise connect to your HPC or cluster. Instead you would use the resources available on your own computer to perform the necessary computations or tasks. This approach allows you to better control the computing environment in addition to having privileges like root access. This is how I was able to freshly install the software on a different Windows PC and process your linked BAM file. 

Additionally, please reconsider the attached log file. It has no error messages or warnings and I'm not sure how it relates to the warnings you posted above it. 

Best regards

**Comment by arodel21** [comment]
Thanks for all the support @JWolpe

I ran the same command this time on my laptop and I am getting the same errors. SeqOutBias and SeqOutATACBias are both properly installed.

I really don't know what else to do...

**Comment by guertinlab** [comment]
> Hi again @JWolpe!
> 
> I got seqOutBias working now! So I ran the program again in a local machine from the cluster that I am working on. I am still getting the same errors though:
> 
> ```
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> /usr/bin/bash: line 1: GRCz11.fa: command not found
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXNNNNNNCNXXXXXXXXXXXXXXXXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXNNNNNCNNXXXXXXXXXXXXXXXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXNNNNCNNNXXXXXXXXXXXXXXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXNNNCNNNNXXXXXXXXXXXXXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXNNCNNNNNXXXXXXXXXXXXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCNNNNNNNXXXXXXXXXXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXNNNNNNNXXXXXXXXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXNNNNNNNXXXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXXNNNNNNNXXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXXXNNNNNNNXXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXXXXNNNNNNNXXXXXX.bigWig
> Couldn't open clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXXXXXXXCXXXXXXXXXXXXNNNNNNNXXXX.bigWig
> Error: The requested file (clean_merged_Citrine_ATAC_Jul2015_zv10_XXXXXXXXXXXXXXXXXNNNNNNCNXXXXXXXXXXXXXXXXXXXXXX.bedGraph) could not be opened. Error message: (No such file or directory). Exiting!
> ```
> 
> I have attached the log here [seqout_log.txt](https://github.com/guertinlab/Tn5bias/files/14523571/seqout_log.txt)
> 
> I really don't know how to proceed... Any advice would be welcomed

There is no error in this log, could you please provide more context?

Line 1 of whatever you are running thinks that "GRCz11.fa" is a command that you are running. Is it possible that there is a carriage return in your command?

**Comment by arodel21** [comment]
Dear @guertinlab and @JWolpe 

Thank you so much for all your support.

In the last line of my previous log there is an error.

Besides that, I managed to finally get seqOutATACBias running on the subsample. One thing that helped was running the command from the same folder where the data was located.

However, when I run seqOutATACBias in the full sample, I get the following error
`Error producing BigWig file: An error occurred running: wigToBigWig -keepAllChromosomes "ATACseq_NCC_Citrine-Cherry_DanRer11_XXXXXXXXXXXXXXXXXXXXXXXCXXNNNNNNNXXXXXXXXXXXXXX.bigWig" "wiggle0clKP.tmp" "chromInfo3CfXx.tmp"`

Which is odd because wigToBigWig should be ran as 
`wigToBigWig -keepAllChromosomes "wiggle0clKP.tmp" "chromInfo3CfXx.tmp" "ATACseq_NCC_Citrine-Cherry_DanRer11_XXXXXXXXXXXXXXXXXXXXXXXCXXNNNNNNNXXXXXXXXXXXXXX.bigWig"`

Do you have idea of where should I look for the origin of this error?

Thanks again.
Best wishes

**Comment by guertinlab** [comment]
Yes, you need to specify the full or relative path structure to the files or run it in the directory containing the files. Can you confirm that `wigToBigWig` is installed and in your $PATH?

**Comment by arodel21** [comment]
Hi again @guertinlab! And thank you so much for your support.

wigToBigWig is indeed installed.

The weird thing is that these errors happen only on my full dataset file and not on the subsample that I sent you.

Could you tell me what is the pipeline that follows after the print
`scale produced atac_file_unscaled.bigWig`

The errors happen right after that line.

Thanks again!

**Comment by guertinlab** [comment]
two things:
-this suggests that the error is in the input files, not the software. 
-can you confirm that "atac_file_unscaled.bigWig" was generated successfully?
